services:
  backend:
    build:
      context: ./backend
    container_name: django_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  web:
    build:
      context: ./webapp
    container_name: react_web
    ports:
      - "3000:3000"
    volumes:
      - ./webapp:/app
      - /app/node_modules

  mobile:
    build:
      context: ./mobile
    container_name: react_mobile
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./mobile:/app
      - /app/node_modules

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: